# Development overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.dev.yml up

services:
  # Development-specific overrides for Redis
  redis:
    container_name: downloadarr-redis-dev
    volumes:
      - redis_data_dev:/data

  # Development-specific overrides for PostgreSQL
  postgres:
    container_name: downloadarr-postgres-dev
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  # Development-specific overrides for API
  api:
    build:
      dockerfile: packages/api/Dockerfile.dev
    container_name: downloadarr-api-dev
    environment:
      NODE_ENV: development
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:3000}
    volumes:
      # Inherit base volumes from docker-compose.yml
      - ${DOWNLOAD_PATH}:/app/downloads
      - ${LIBRARY_PATH}:/app/library
      - ./config:/app/config:ro
      # Add development-specific volumes
      - ./packages/api/src:/app/packages/api/src:ro
      - ./packages/api/prisma:/app/packages/api/prisma

  # Development-specific overrides for Frontend
  frontend:
    build:
      dockerfile: packages/ui/Dockerfile.dev
    container_name: downloadarr-frontend-dev
    environment:
      DOCKER_ENV: "true"
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3001}
    volumes:
      # Mount source code for hot reloading
      - ./packages/ui/src:/app/packages/ui/src:ro

  # Development-specific overrides for Jackett
  jackett:
    container_name: downloadarr-jackett-dev
    volumes:
      # Inherit base volumes from docker-compose.yml
      - jackett_config_dev:/config
      - jackett_config_dev:/jackett-config
      - ${DOWNLOAD_PATH}:/downloads

  # Development-specific overrides for Aria2
  aria2:
    container_name: downloadarr-aria2-dev
    volumes:
      # Inherit base volumes from docker-compose.yml
      - aria2_config_dev:/config
      - ${DOWNLOAD_PATH}:/downloads

  # Development-specific overrides for AriaNG
  ariang:
    container_name: downloadarr-ariang-dev

# Development-specific volumes
volumes:
  redis_data_dev:
  postgres_data_dev:
  jackett_config_dev:
  aria2_config_dev:
